# Generated by Django 4.1.6 on 2023-02-11 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_order_options_remove_order_paid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('created',), 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
