# Generated by Django 4.1.6 on 2023-02-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_post_subtitle_alter_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('short_description', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('kind', models.CharField(choices=[('m', 'motor'), ('t', 'transmission'), ('h', 'hydraulic')], max_length=1)),
                ('image', models.ImageField(blank=True, upload_to='uploads')),
            ],
        ),
    ]
