# Generated by Django 4.1.6 on 2023-02-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_oils_oil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oil',
            name='kind',
            field=models.CharField(choices=[('m', 'Motor oils'), ('t', 'Transmission oils'), ('h', 'Hydraulic oils'), ('g', 'Greases')], max_length=1),
        ),
    ]
