# Generated by Django 4.1.5 on 2023-02-24 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(max_length=500)),
                ('tuesday', models.CharField(max_length=500)),
                ('wednesday', models.CharField(max_length=500)),
                ('thursday', models.CharField(max_length=500)),
                ('friday', models.CharField(max_length=500)),
                ('saturday', models.CharField(max_length=500)),
                ('sunday', models.CharField(max_length=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasteandshare.author')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100, verbose_name='Recipe name')),
                ('recipe_type', models.CharField(choices=[('sl', 'Salad'), ('sp', 'Soup'), ('hd', 'Hot dish'), ('ds', 'Dessert'), ('ps', 'Pasta'), ('pz', 'Pizza')], max_length=10, verbose_name='Recipe type')),
                ('calories', models.CharField(max_length=30, verbose_name='Calories')),
                ('time', models.CharField(max_length=4, verbose_name='Time')),
                ('preparation', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='uploads')),
                ('issued', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasteandshare.author')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('comment', models.TextField()),
                ('issued', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasteandshare.author')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasteandshare.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='ProhibitedFoodstuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasteandshare.author')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('amount', models.CharField(max_length=50, verbose_name='Amount')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasteandshare.recipe')),
            ],
        ),
    ]
