# Generated by Django 4.1.5 on 2023-02-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_customer_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
