# Generated by Django 4.1.5 on 2023-02-09 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_products_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='product_type',
            new_name='catalog_name',
        ),
        migrations.AlterField(
            model_name='products',
            name='product_type',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='main_site.catalog'),
        ),
    ]
