# Generated by Django 4.1.5 on 2023-02-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_bascet'),
    ]

    operations = [
        migrations.AddField(
            model_name='bascet',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
