# Generated by Django 4.1.5 on 2023-02-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0007_alter_bascet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bascet',
            name='description',
            field=models.TextField(default='<django.db.models.query_utils.DeferredAttribute object at 0x11816c510>'),
        ),
    ]
