# Generated by Django 4.1.5 on 2023-02-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0008_alter_bascet_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bascet',
            name='description',
            field=models.TextField(),
        ),
    ]
