# Generated by Django 4.1.5 on 2023-02-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0010_alter_products_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='catalog_name',
            field=models.TextField(unique=True),
        ),
    ]
